//
//  TempleCardDeck.swift
//  Project2 Clark Branden
//
//  Created by Branden Clark on 10/17/18.
//  Copyright © 2018 Branden Clark. All rights reserved.
//

import Foundation

class TempleDeck {
    
    //MARK: - Properties
    var temples: [TempleCard] = [
        TempleCard(fileName: "aba-nigeria-temple-lds-273999-mobile.jpg",
                   name: "Aba",
                   region: "Nigeria"),
        TempleCard(fileName: "accra-ghana-temple-lds-249027-mobile.jpg",
                   name: "Accra",
                   region: "Ghana"),
        TempleCard(fileName: "albuquerque-temple-lds-137885-mobile.jpg",
                   name: "Albuquerque",
                   region: "New Mexico"),
        TempleCard(fileName: "anchorage-temple-lds-253274-mobile.jpg",
                   name: "Anchorage",
                   region: "Alaska"),
        TempleCard(fileName: "apia-samoa-temple-lds-460475-mobile.jpg",
                   name: "Apia",
                   region: "Samoa"),
        TempleCard(fileName: "asuncion-paraguay-temple-lds-298372-mobile.jpg",
                   name: "Asunción",
                   region: "Paraguay"),
        TempleCard(fileName: "atlanta-georgia-temple-sunset-1218213-mobile.jpg",
                   name: "Atlanta",
                   region: "Georgia"),
        TempleCard(fileName: "baton-rouge-temple-lds-1078084-mobile.jpg",
                   name: "Baton Rouge",
                   region: "Louisiana"),
        TempleCard(fileName: "bern-switzerland-temple-lds-653038-mobile.jpg",
                   name: "Bern",
                   region: "Switzerland"),
        TempleCard(fileName: "bismarck-temple-lds-408056-mobile.jpg",
                   name: "Bismarck",
                   region: "North Dakota"),
        TempleCard(fileName: "bogota-colombia-mormon-temple-856490-mobile.jpg",
                   name: "Bogotá",
                   region: "Colombia"),
        TempleCard(fileName: "boise-temple-lds-39439-mobile.jpg",
                   name: "Boise",
                   region: "Idaho"),
        TempleCard(fileName: "boston-temple-lds-945541-mobile.jpg",
                   name: "Boston",
                   region: "Massachusetts"),
        TempleCard(fileName: "bountiful-temple-766491-mobile.jpg",
                   name: "Bountiful",
                   region: "Utah"),
        TempleCard(fileName: "brigham-city-utah-temple-dedication-day-1027033-mobile.jpg",
                   name: "Brigham City",
                   region: "Utah"),
        TempleCard(fileName: "brisbane-australia-temple-lds-745088-mobile.jpg",
                   name: "Brisbane",
                   region: "Australia"),
        TempleCard(fileName: "buenos-aires-argentina-temple-lds-82744-mobile.jpg",
                   name: "Buenos Aires",
                   region: "Argentina"),
        TempleCard(fileName: "calgary-alberta-temple-before-open-house-1033408-mobile.jpg",
                   name: "Calgary",
                   region: "Alberta"),
        TempleCard(fileName: "campinas-brazil-temple-lighted-1029894-mobile.jpg",
                   name: "Campinas",
                   region: "Brazil"),
        TempleCard(fileName: "cardston-alberta-temple-lds-782043-mobile.jpg",
                   name: "Cardston",
                   region: "Alberta"),
        TempleCard(fileName: "cebu-philippines-temple-lds-852837-mobile.jpg",
                   name: "Cebu City",
                   region: "Philippines"),
        TempleCard(fileName: "chicago-temple-lds-885844-mobile.jpg",
                   name: "Chicago",
                   region: "Illinois"),
        TempleCard(fileName: "ciudad-juarez-mexico-temple-lds-126122-mobile.jpg",
                   name: "Ciudad Juárez",
                   region: "Mexico"),
        TempleCard(fileName: "columbia-river-temple-lds-761262-mobile.jpg",
                   name: "Columbia River",
                   region: "Washington"),
        TempleCard(fileName: "columbia-temple-lds-83400-mobile.jpg",
                   name: "Columbia",
                   region: "South Carolina"),
        TempleCard(fileName: "columbus-temple-lds-406110-mobile.jpg",
                   name: "Columbus",
                   region: "Ohio"),
        TempleCard(fileName: "copenhagen-denmark-temple-895949-mobile.jpg",
                   name: "Copenhagen",
                   region: "Denmark"),
        TempleCard(fileName: "cordoba-argentina-temple-rendering-780527-mobile.jpg",
                   name: "Córdoba",
                   region: "Argentina"),
        TempleCard(fileName: "curitiba-brazil-temple-lds-851199-mobile.jpg",
                   name: "Curitiba",
                   region: "Brazil"),
        TempleCard(fileName: "dallas-temple-lds-850748-mobile.jpg",
                   name: "Dallas",
                   region: "Texas"),
        TempleCard(fileName: "denver-temple-lds-999518-mobile.jpg",
                   name: "Denver",
                   region: "Colorado"),
        TempleCard(fileName: "detroit-temple-lds-837623-mobile.jpg",
                   name: "Detroit",
                   region: "Michigan"),
        TempleCard(fileName: "draper-utah-lds-temple-1079449-mobile.jpg",
                   name: "Draper",
                   region: "Utah"),
        TempleCard(fileName: "guatemala-lds-temple-82739-mobile.jpg",
                   name: "Edmonton",
                   region: "Alberta"),
        TempleCard(fileName: "helsinki-finland-temple-lds-354503-mobile.jpg",
                   name: "Helsinki",
                   region: "Finland"),
        TempleCard(fileName: "kyiv-ukraine-temple-lds-774302-mobile.jpg",
                   name: "Kyiv",
                   region: "Ukraine"),
        TempleCard(fileName: "hawaii-temple-761091-mobile.jpg",
                   name: "Laie",
                   region: "Hawaii"),
        TempleCard(fileName: "madrid-spain-temple-954939-mobile.jpg",
                   name: "Madrid",
                   region: "Spain"),
        TempleCard(fileName: "mexico-city-temple-lds-591669-mobile.jpg",
                   name: "Mexico City",
                   region: "Mexico")
        ]

    //MARK: - Helpers
    func remove(at index: Int) {
        temples.remove(at: index)
    }
    
    func shuffle() {
        temples.shuffle()
    }
}
